
-- Business Analysis

-- Q1. What is the total revenue generated by male vs female customers ?

SELECT 
		gender,
		SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount ?

SELECT
		customer_id,
		purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) AS Avg_Purchase_Amount FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating ?

SELECT
		item_purchased AS Product,
		ROUND(
		AVG(review_rating)::numeric
		,2) AS Average_Review_Rating
FROM customer
GROUP by 1
ORDER BY 2 DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between standard and express shipping

SELECT
		shipping_type,
		ROUND(AVG(purchase_amount),2) AS Average_Purchase_Amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
Group BY shipping_type;


-- Q5. Do subsribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT
		subscription_status,
		COUNT(customer_id) AS Total_Customers,
		ROUND(AVG(purchase_amount),2) AS Average_Spend,
		ROUND(SUM(purchase_amount),2) AS Total_Revenue
FROM customer
GROUP BY 1
ORDER BY 4,3 DESC;


-- Q6. Which 5 products have the highes percentage of purchases with discounts applied ?

SELECT
		item_purchased AS Products,
		ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS Discount_Rate
FROM customer
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS 
(
	SELECT 
			customer_id,
			previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
			END AS Customer_Segment
	FROM customer
)
SELECT
		customer_segment,
		COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY 1;
)


-- Q8. What are the top 3 most purchased products within each category

WITH item_count AS
(
	SELECT 
			category,
			item_purchased,
			COUNT(customer_id) AS Total_Orders,
			ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS Item_Rank
	FROM customer
	GROUP BY 1,2
)
SELECT
		Item_Rank,
		category,
		item_purchased,
		Total_Orders
FROM item_count
WHERE Item_Rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT
		subscription_status,
		COUNT(customer_id) AS Repeat_Buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY 1;


-- Q10. What is the revenue contribution of each age group ?

SELECT
		age_group,
		SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY 1
ORDER BY 2 DESC;
